name: Run script in Docker container
on: [workflow_dispatch]
jobs:
  run-script:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus
    env:
      MY_SECRET: ${{ secrets.URL }}
    steps:
      - name: Run SFDX
        run: |
          sfdx --version
          echo MY_SECRET
          echo ${{ secrets.URL }}
