name: Check SFDX Deploy without Docker
on: [workflow_dispatch]
jobs:
  call-workflow-passing-data:
    uses: MichaelPStimpson/actions/.github/workflows/deploy-sf-env.yml@main
    with:
      sandbox: false
      check-only: true
      run-scan: true
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
