name: Check SFDX Deploy
on: [workflow_dispatch]
jobs:
  run-script:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
    steps:
      - name: Auth Dev Org
        run: |
          echo $JWT > ~/server.key
          sfdx force auth jwt grant --client-id $CONSUMER_KEY --jwt-key-file ~/server.key --username $USERNAME --instance-url $URL -s
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Check Deployment
        run: sfdx force source deploy -checkonly
