name: CALLABLE scan, deploy, and test against salesforce environment
on:
  workflow_call:
    inputs:
      #Determines the SFDX_AUDIENCE_URL
      sandbox:
        required: true
        type: boolean
      #Run checkonly deployment
      check-only:
        required: true
        type: boolean
      #Run sfdx-scanner
      run-scan:
        required: true
        type: boolean
      #Run local tests
      run-tests:
        required: true
        type: boolean
    secrets:
      CONSUMER_KEY:
        required: true
      USERNAME:
        required: true
      URL:
        required: true
      JWT:
        required: true

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    #Container has OpenJdk17, Python3, Curl, JQ, SFDX, SFDX-Hardis, SFDX-Scanner, SFDX-Git-Delta
    container: michaelpstimpson/sf-pipeline:full
    steps:
      #Typescript error on docker build, version mismatch
      - name: Check plugins
        run: |
          sfdx plugins

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan Code
        if: ${{ inputs.run-scan == true }}
        run: |
          sfdx scanner:run \
          --target "force-app" \
          --format "json" \
          --category Security > ~/sfdx-scanner-report.json
          cat ~/sfdx-scanner-report.json
          if ! grep -q "No rule violations found." ~/sfdx-scanner-report.json; then
            exit 1
          fi

      - name: Auth Salesforce Environment
        run: |
          if [ ${{ inputs.sandbox }} = true ]; then
            echo "SFDX_AUDIENCE_URL=https://test.salesforce.com" >> $GITHUB_ENV
          else
            echo "SFDX_AUDIENCE_URL=https://login.salesforce.com" >> $GITHUB_ENV
          fi
          echo "$JWT" > ~/server.key
          sfdx force auth jwt grant \
          --client-id $CONSUMER_KEY \
          --jwt-key-file ~/server.key \
          --username $USERNAME \
          --instance-url $URL \
          -s
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          URL: ${{ secrets.URL }}
          JWT: ${{ secrets.JWT }}

      - name: Create Packages
        run: |
          git config --global --add safe.directory /__w/actions/actions

          BASE="origin/${{ github.base_ref }}"
          HEAD="origin/${{ github.head_ref }}"
          MERGE_BASE=$(git merge-base $BASE $HEAD)

          echo "The base SHA is: $BASE"
          echo "The head SHA is: $HEAD"
          echo "The MERGE_BASE SHA is: $MERGE_BASE"

          mkdir ~/manifest
          sfdx sgd:source:delta \
          --to $HEAD \
          --from $MERGE_BASE \
          --source force-app \
          --output ~/manifest \
          --ignore .sgdignore \
          --ignore-destructive .sgdignoreDestructive

          echo "----PACKAGE START----"
          cat ~/manifest/package/package.xml
          echo "----PACKAGE END----"
          echo "----DESTRUCTIVE PACKAGE START----"
          cat ~/manifest/destructiveChanges/destructiveChanges.xml
          echo "----DESTRUCTIVE PACKAGE END----"

      - name: Deployment
        #TODO: Add HARDIS after resolving test class issues.
        #TODO: Replace commands with a single eval.
        run: |
          if ! grep -q "<members>" ~/manifest/package/package.xml \
          && ! grep -q "<members>" ~/manifest/destructiveChanges/destructiveChanges.xml; then
            echo "No components to deploy."
            exit 0
          fi
          if [ ${{ inputs.check-only }} = true ] && [ ${{ inputs.run-tests }} = true ]; then
            sfdx force source deploy \
            --manifest ~/manifest/package/package.xml \
            --postdestructivechanges ~/manifest/destructiveChanges/destructiveChanges.xml \
            --checkonly \
            --testlevel=RunLocalTests
          elif [ ${{ inputs.check-only }} = false ] && [ ${{ inputs.run-tests }} = false ]; then
            sfdx force source deploy \
            --manifest ~/manifest/package/package.xml \
            --postdestructivechanges ~/manifest/destructiveChanges/destructiveChanges.xml
          elif [ ${{ inputs.check-only }} = true ] && [ ${{ inputs.run-tests }} = false ]; then
            sfdx force source deploy \
            --manifest ~/manifest/package/package.xml \
            --postdestructivechanges ~/manifest/destructiveChanges/destructiveChanges.xml \
            --checkonly
          elif [ ${{ inputs.check-only }} = false ] && [ ${{ inputs.run-tests }} = true ]; then
            sfdx force source deploy \
            --manifest ~/manifest/package/package.xml \
            --postdestructivechanges ~/manifest/destructiveChanges/destructiveChanges.xml \
            --testlevel=RunLocalTests
          fi
