name: Check Pull Request
on:
  pull_request:
    branches:
      - env/dev
      - env/qa
      - env/prod
    types:
      - opened
      - edited
      - synchronize
      - reopened

env:
  dev: env/dev
  qa: env/qa
  prod: env/prod

jobs:
  dev-workflow:
    if: contains($GITHUB_BASE_REF, ${{ env.dev }})
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  qa-workflow:
    if: contains($GITHUB_BASE_REF, ${{ env.qa }})
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  prod-workflow:
    if: contains($GITHUB_BASE_REF, ${{ env.prod }})
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: false
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
