name: check-pr
run-name: Checking ${{ github.actor }}'s PR. #github.base_ref
on:
  pull_request:
    branches:
      - main
      - 'env/*'
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g sfdx-cli
      - run: echo 'y' | sfdx plugins:install @salesforce/sfdx-scanner, sfdx-hardis, sfdx-git-delta

  code-scanner:
    name: Scan Code With SFDX Scanner
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - run: sfdx scanner:run --target "force-app/**" --format table --category Security --severity-threshold 1

  test-build:
    name: Validate + Test Deployment
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - run: sfdx hardis:org:test:apex --testlevel RunSpecifiedTests --classnames "Topics_Test"
