name: Check Pull Request
on:
  pull_request_target:
    branches:
      - env/qa
      - env/prod
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  qa-workflow:
    if: ${{ contains(github.ref, env/qa) }}
    uses: ./.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}
  prod-workflow:
    if: ${{ contains(github.ref, env/prod) }}
    uses: ./.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: false
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
