name: Check Pull Request
on:
  pull_request:
    branches:
      - env/dev
      - env/qa
      - env/prod
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  dev-workflow:
    if: ${{ github.base_ref == 'env/dev' }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  qa-workflow:
    if: ${{ github.base_ref == 'env/qa' }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  prod-workflow:
    if: ${{ github.base_ref == 'env/prod' }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: false
      check-only: true
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
