name: 'Colton job'

on: workflow_dispatch

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install Salesforce CLI
        run: | 
          npm install --global xml2js xml-buffer-tostring
          npm list -g --depth=0
          npm root
          ls
          ls ~/work/actions/actions/node_modules
          ls ./work/actions/actions/node_modules
          ls | npm root
          npm link ~/work/actions/actions/node_modules/xml-buffer-tostring@0.2.0
          npm link ~/work/actions/actions/node_modules/xml2js@0.5.0

      - name: Run my script
        run: |
           node scripts/my-test.js > ~/results.txt
           cat ~/results.txt
