name: 'Colton job'

on: workflow_dispatch

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install Salesforce CLI
        run: | 
          npm install --global xml2js xml-buffer-tostring
          npm list -g --depth=0
          npm root -g
          cd /opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules
          pwd
          dir
          ls | npm root -g
          npm link xml2js
          npm link xml-buffer-tostring
          

      - name: Run my script
        run: |
           node scripts/my-test.js > ~/results.txt
           cat ~/results.txt
