name: 'Colton job'

on: workflow_dispatch

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install Salesforce CLI
        run: | 
          npm install --global xml2js xml-buffer-tostring
          npm link xml2js
          npm link xml-buffer-tostring

      - name: Run my script
        run: |
           node scripts/my-test.js > ~/results.txt
           cat ~/results.txt
