name: 'Colton job'

on: workflow_dispatch

jobs:
  test-script:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

     # - name: Install npm
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: 18
      #- name: Install salesforce
      #  run: npm install -g sfdx-cli
      
     # - name: Install Delta
     #   run: sfdx plugins install @salesforce/sfdx-scanner
     
      - name: Loop over files and copy them
        run: |
          INPUT_FILES="SampleClass.cls"
          for file in $(echo $INPUT_FILES | tr ',' ' '); do
            find . -type f -name $file -exec cp {} ~/temp/ \;
          done

     # - name: pwd
     #   run: pwd
        
     # - name: Prints
     #   run: ls ~
        
     # - name: Prints 2
     #   run: ls ~/work
        
     # - name: Prints 3
      #  run: ls ~/runners
        
     # - name: Run my script
     #   run: npm install -g sfdx-cli
        
      #- name: Install plugins
     #   run: sfdx plugins install sfdx-git-delta
