name: Create Pull Request
on:
  schedule:
    - cron: "0 17,21 * * 1-5" #1PM & 5PM EST Monday through Friday
    - cron: "0 16 * * 5" #12PM EST Friday
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "QA"
        type: choice
        options:
          - QA
          - UAT
          - TRAIN
          - PROD
jobs:
  call-create-pr-for-qa:
    if: github.event.schedule == '0 17,21 * * 1-5' || inputs.environment == 'QA'
    uses: MichaelPStimpson/actions/.github/workflows/callable-create-pr.yml@main
    with:
      base: "env/qa"
      head: "env/dev"
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  call-create-pr-for-uat:
    if: github.event.schedule == '0 16 * * 5' || inputs.environment == 'UAT'
    uses: MichaelPStimpson/actions/.github/workflows/callable-create-pr.yml@main
    with:
      base: "env/uat"
      head: "env/qa"
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  call-create-pr-for-train:
    if: github.event.schedule == '0 16 * * 5' || inputs.environment == 'TRAIN'
    uses: MichaelPStimpson/actions/.github/workflows/callable-create-pr.yml@main
    with:
      base: "env/train"
      head: "env/uat"
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  call-create-pr-for-prod:
    if: github.event.schedule == '0 16 * * 5' || inputs.environment == 'PROD'
    uses: MichaelPStimpson/actions/.github/workflows/callable-create-pr.yml@main
    with:
      base: "env/prod"
      head: "env/uat"
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
