name: create-pr
on:
  workflow_dispatch:

jobs:
  create-pull-request:
    name: Create pull request
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        run: |
          git config --global --add safe.directory /__w/actions/actions
          git config user.email "MichaelPStimpson@outlook.com"
          git config user.name "Michael Stimpson"
          RELEASE_NAME="release/main-$(date '+%Y%m%d_%H%M')"
          git checkout -b $RELEASE_NAME
          git merge -X theirs origin/dev
          gh pr create --help
          PR_NUMBER=gh pr create \
          -t "Automated PR" \
          -b ":rocket :robot:" \
          -B main \
          -H RELEASE_NAME \
          -l auto-pr \
          -r MichaelPStimpson
          echo "The PR Number is: $PR_NUMBER"
      # - name: Create Pull Request
      #   run: |
      #     gh pr create \
      #     --title "Automated PR" \
      #     --body ":rocket :robot:" \
      #     --base main \
      #     --head dev \
      #     --label auto-pr \
      #     --reviewer MichaelPStimpson
