name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  call-create-pr:
    uses: MichaelPStimpson/actions/.github/workflows/callable_create_pr.yml@main
    with:
      base: "main"
      head: "origin/dev"
