name: Deploy push to salesforce environment
on:
  push:
    branches:
      - env/qa
      - env/uat
      - env/train
      - env/prod

jobs:
  qa-workflow:
    if: ${{ contains(github.ref, env/qa) }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: false
      run-scan: false
      run-tests: true
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  uat-workflow:
    if: ${{ contains(github.ref, env/uat) }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: false
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  train-workflow:
    if: ${{ contains(github.ref, env/train) }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: true
      check-only: false
      run-scan: false
      run-tests: false
    secrets:
      CONSUMER_KEY: ${{ secrets.QA_CONSUMER_KEY }}
      USERNAME: ${{ secrets.QA_USERNAME }}
      URL: ${{ secrets.QA_URL }}
      JWT: ${{ secrets.JWT }}

  prod-workflow:
    if: ${{ contains(github.ref, env/prod) }}
    uses: MichaelPStimpson/actions/.github/workflows/callable-scan-deploy-to-sf.yml@main
    with:
      sandbox: false
      check-only: false
      run-scan: true
      run-tests: true
    secrets:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      URL: ${{ secrets.URL }}
      JWT: ${{ secrets.JWT }}
