name: Deploy to Salesforce Environment
on:
  workflow_call:
    inputs:
      sandbox:
        required: true
        type: boolean
      check-only:
        required: true
        type: boolean
      run-scan:
        required: true
        type: boolean
      run-tests:
        required: true
        type: boolean
    secrets:
      CONSUMER_KEY:
        required: true
      USERNAME:
        required: true
      URL:
        required: true
      JWT:
        required: true

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Scan Code
        if: ${{ inputs.run-scan == true }}
        run: |
          echo $SFDX_AUDIENCE_URL
          sfdx scanner:run --target "force-app/**/*.{cls,trigger,js}" --format "json" --category Security | cat sfdx-scanner-report.json
          if [ $(jq '.violations | length' sfdx-scanner-report.json) -ne 0 ]; then
            cat sfdx-scanner-report.json
            exit 1
          else
            echo "No violations found!"
        fi

      - name: Set Audience URL
        run: |
          if [ "${{ inputs.sandbox }}" == true]; then
            echo "SFDX_AUDIENCE_URL=https://test.salesforce.com" >> $GITHUB_ENV
          else
            echo "SFDX_AUDIENCE_URL=https://login.salesforce.com" >> $GITHUB_ENV
          fi

      - name: Auth Salesforce Environment
        run: |
          echo "$JWT" > ~/server.key
          sfdx force auth jwt grant \
          --client-id $CONSUMER_KEY \
          --jwt-key-file ~/server.key \
          --username $USERNAME \
          --instance-url $URL \
          -s
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          URL: ${{ secrets.URL }}
          JWT: ${{ secrets.JWT }}

      - name: Deployment
        run: |
          DEPLOY_COMMAND="sfdx force source deploy --sourcepath force-app"
          if [ "${{ inputs.check-only }}" == true]; then
            DEPLOY_COMMAND += " --checkonly"
          fi
          if [ "${{ inputs.run-tests }}" == true]; then
            DEPLOY_COMMAND += " --testlevel=RunLocalTests"
          fi
          echo "Deploy command: $DEPLOY_COMMAND"
          eval "$DEPLOY_COMMAND"
