name: Deploy to Salesforce Environment
on:
  workflow_call:
    inputs:
      sandbox:
        required: true
        type: boolean
      check-only:
        required: true
        type: boolean
      run-scan:
        required: true
        type: boolean
      run-tests:
        required: true
        type: boolean
      min-test-coverage:
        required: false
        type: number
    secrets:
      CONSUMER_KEY:
        required: true
      USERNAME:
        required: true
      URL:
        required: true
      JWT:
        required: true

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sfdx-plus
    steps:
      - name: Auth Salesforce Environment
        run: |
          echo "$JWT" > ~/server.key
          sfdx force auth jwt grant \
          --client-id $CONSUMER_KEY \
          --jwt-key-file ~/server.key \
          --username $USERNAME \
          --instance-url $URL \
          -s
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          URL: ${{ secrets.URL }}
          JWT: ${{ secrets.JWT }}
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deployment
        run: |
          echo $SFDX_AUDIENCE_URL
          if [ "${{ inputs.check-only }}" == true]; then
            sfdx force source deploy \
            --sourcepath force-app \
            --checkonly 
          else
            sfdx force source deploy \
            --sourcepath force-app
          fi
