create-package:
  name: Create package xml with SFDX Git Delta
  runs-on: ubuntu-latest
  needs: [install-dependencies]
  steps:
    - run: sfdx scanner:run --target "force-app/**" --format table --category Security --severity-threshold 1
name: create-pr
run-name: ${{ github.actor }} is creating a PR.
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g sfdx-cli
      - run: echo 'y' | sfdx plugins:install sfdx-git-delta

  create-pull-request:
    name: Create pull request to ${{ github.event.inputs.targetEnv }}
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Deploying to ${{ github.event.inputs.targetEnv }}
      - if: ${{ contains(github.event.inputs.targetEnv, 'dev') }}
      - run: sfdx force source deploy
