name: Main Deploy

on:
  push:
    branches:
      - main
    paths:
      - "force-app/**"

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    container: michaelpstimpson/sf-pipeline:full

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate
        run: |
          echo "$AUTH_URL" > ~/AUTH_URL
          sfdx org login sfdx-url -f ~/AUTH_URL -s
        env:
          AUTH_URL: ${{ secrets.QA_AUTH_KEY }}

      - name: Build & test
        run: |
          sf force source deploy -p force-app --checkonly --testlevel=RunLocalTests
          sf project deploy quick -r
