name: TESTING PR
on:
  pull_request:
    branches:
      - "*"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    #Container has OpenJdk17, Python3, Curl, JQ, SFDX, SFDX-Hardis, SFDX-Scanner, SFDX-Git-Delta
    container: michaelpstimpson/sfdx-plus:latest
    steps:
      - name: Create Pull Request
        run: |
          echo "THE BASE IS ${{ github.sha }}""
          echo "The HEAD IS ${{ github.event.pull_request.head.sha }}"
