name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #Container has OpenJdk17, Python3, Curl, JQ, SFDX, SFDX-Hardis, SFDX-Scanner, SFDX-Git-Delta
    container: michaelpstimpson/sf-pipeline:base
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
