name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #Container has OpenJdk17, Python3, Curl, JQ, SFDX, SFDX-Hardis, SFDX-Scanner, SFDX-Git-Delta
    container: michaelpstimpson/sf-pipeline:base
    steps:
      - name: Install sudo
        run: |
          sudo apt-get update
          sudo apt-get install sudo

      - uses: actions/checkout@v3

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
